### ISSUE TITLE
无法正常观看杜比视界

### ISSUE THREAD

**Issue by lns103** [cjw1115/enable-chromium-dolbyvision-system-decoding#2]
已添加readme中启动参数并开启MediaFoundation for Clear
尝试过播放b站上的profile 5和profile 8.4的视频，均无法正确显示，且卡在一个画面，拖动进度条会卡在另一个画面，其它的HDR和SDR画质正常播放
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/533c91c0-310d-440a-9697-e2b91785aa8a)
注：设备是联想Y9000k 2020，自带杜比视界授权，相关视频下载之后用自带播放器正常播放
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/0fb36488-d38d-4aa8-85cf-d5f8d26c85c8)
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/59be3a58-0c5c-493b-a552-bfb38a506ac1)

还发现一个问题，这个浏览器没法观看本地视频，将本地mp4拖进去无法播放

**Comment by lns103** [comment]
另外还发现了用MediaFoundation解码的一些显示bug，如果在 chrome://flags/#force-color-profile 设置 sRGB，播放SDR视频，全屏之后，在播放控件消失的一瞬间，色彩会突变，黑色会变深，然后恢复，控件出现的时候正常。
如果是配置了校色文件的广色域屏，那么在显示播放控件时会缩限至sRGB空间，全屏，控件消失时色彩会突变，黑色会变深，然后会在原生色域播放，在控件出现时又重新恢复sRGB缩限
（这个bug应该影响不大，反正到时候chrome肯定不会用MediaFoundation来放普通视频）

**Comment by cjw1115** [comment]
你用chrome://media-internals 看看播放时的log，贴一下我看看

**Comment by lns103** [comment]
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/f5a2b476-50eb-4f07-bc4f-f6a363ef218f)

**Comment by cjw1115** [comment]
> ![image](https://user-images.githubusercontent.com/49310852/250138973-f5a2b476-50eb-4f07-bc4f-f6a363ef218f.png)

渲染模式是错误的，你看看你在 chrome://flags 里面除了 media foundation for clear, 还开了什么选项，就你改过的

**Comment by lns103** [comment]
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/165800c1-ec3f-467b-b535-0aaeac9ad5c3)
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/a524069b-f1c4-40b5-b28c-4eccee143633)
没开别的

**Comment by cjw1115** [comment]
看起来也是正常的，方便的话可以用teams之类的远程看看啥情况，我这边几台机器没复现出这个现象

**Comment by lns103** [comment]
> 看起来也是正常的，方便的话可以用teams之类的远程看看啥情况，我这边几台机器没复现出这个现象

可以，请问如何联系？

**Comment by cjw1115** [comment]
> > 看起来也是正常的，方便的话可以用teams之类的远程看看啥情况，我这边几台机器没复现出这个现象
> 
> 可以，请问如何联系？

你给我发邮件吧，cjw1115@hotmail.com

**Comment by cjw1115** [comment]
感谢 @lns103 报告这个问题。 

经过和@Ins103 同学一起测试后发现，如果电脑同时安装了两个杜比视界的扩展包，就会出现绿屏卡顿问题。
原因是这种情况下，两个杜比视界的解码器都不会被加载。

如果遇到了这个问题，可以用以下办法排查解决：
1. 用管理员权限打开 `PowerShell`, 执行以下命令：
```
Get-AppxPackage -AllUsers *DolbyVision*
```
2. 检查输出的结果中有几个 Dolby Vision 的安装包（如果你遇到了这个问题，大概率是会有两个，一个叫做DolbyVisionAccess，另一个叫做DolbyVisionHDR ）, 大致如下：
```
Name                   : DolbyLaboratories.DolbyVisionAccess
Publisher              : CN=58D26209-1D57-482C-B403-B655571B5C7B
Architecture           : X64
ResourceId             : 
Version                : 2.2.320.0
PackageFullName        : DolbyLaboratories.DolbyVisionAccess_2.2.320.0_x64__rz1tebttyb220
InstallLocation        : C:\Program Files\WindowsApps\DolbyLaboratories.DolbyVisionAccess_2.2.320.0_x64__rz1tebttyb220
IsFramework            : False
PackageFamilyName      : DolbyLaboratories.DolbyVisionAccess_rz1tebttyb220
PublisherId            : rz1tebttyb220
PackageUserInformation : {S-1-5-21-2917138051-1751375874-2554702744-1001 [cjw11]: Installed}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : False
Dependencies           : {Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe, Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x
                         64__8wekyb3d8bbwe, Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok

Name                   : DolbyLaboratories.DolbyVisionHDR
Publisher              : CN=58D26209-1D57-482C-B403-B655571B5C7B
Architecture           : X64
ResourceId             : 
Version                : 2.2.320.0
PackageFullName        : DolbyLaboratories.DolbyVisionHDR_2.2.320.0_x64__rz1tebttyb220
InstallLocation        : C:\Program Files\WindowsApps\DolbyLaboratories.DolbyVisionHDR_2.2.320.0_x64__rz1tebttyb220
IsFramework            : False
PackageFamilyName      : DolbyLaboratories.DolbyVisionHDR_rz1tebttyb220
PublisherId            : rz1tebttyb220
PackageUserInformation : {S-1-5-21-2917138051-1751375874-2554702744-1001 [cjw11]: Installed}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : False
Dependencies           : {Microsoft.VCLibs.140.00_14.0.32530.0_x64__8wekyb3d8bbwe, Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x
                         64__8wekyb3d8bbwe, Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok
```
3. 将这两个杜比视界扩展包全部卸载，可以去 **设置 - 应用** 里面找到这两个应用，手动卸载。也可以在刚才打开的 `PwoerShell` 里面用如下命令卸载：
```
// 注意 `-AllUsers` 后面的部分是上面查询命令中的 `PackageFullName` 部分
// 两行命令依次执行
Remove-AppPackage -AllUsers  DolbyLaboratories.DolbyVisionHDR_2.2.320.0_x64__rz1tebttyb220
Remove-AppPackage -AllUsers  DolbyLaboratories.DolbyVisionAccess_2.2.320.0_x64__rz1tebttyb220
```
4. 卸载后需要重新安装杜比视界的扩展包，但这次**只需要安装一个**，下面两个中二选一即可：
    - DolbyVisionAccess 无UI版本，主打一个清爽 [DolbyVisionAccess 传送门--->](https://www.microsoft.com/store/apps/9PLTG1LWPHLF)
    - DolbyVisionHDR     有一个简单的UI，可以控制画面的模式  [DolbyVisionHDR 传送门--->](https://www.microsoft.com/store/apps/9MVMZ93N61T9)
5. 重新用 Chrome 播放应该就没问题了

**Comment by lns103** [comment]
补充一下，DolbyVisionAccess没有UI界面，但是可以在Dolby Access的设置中切换画面模式，但是我似乎发现切换画面模式只对于本地播放器有效，对于浏览器播放无效（或者不是实时切换，我看不出来）

**Comment by lns103** [comment]
并且我的 MediaFoundationRenderingMode 还是 Frame Server ，浏览器播放时也没有出现右上角的Dolby Vision logo

**Comment by cjw1115** [comment]
> 并且我的 MediaFoundationRenderingMode 还是 Frame Server ，浏览器播放时也没有出现右上角的Dolby Vision logo

frame server那个不太准确，这版内部有些问题，log输出不太对。

**Comment by cjw1115** [comment]
> 并且我的 MediaFoundationRenderingMode 还是 Frame Server ，浏览器播放时也没有出现右上角的Dolby Vision logo

至于没logo，看起来是另外的一个问题了，可以单开一个issue
