### ISSUE TITLE
切换杜比视界图像模式无效，且播放开始时不显示Dolby Vision logo

### ISSUE THREAD

**Issue by lns103** [cjw1115/enable-chromium-dolbyvision-system-decoding#3]
使用系统自带播放器时可以显示Dolby Vision logo，且切换杜比视界图像模式会实时生效，使用浏览器播放时不行

**Comment by cjw1115** [comment]
你把这个目录删除，然后重新试试看啥情况。（删除后之前的登陆数据之类的就没了）
`C:\Users\{用户名}\AppData\Local\Chromium\User Data`

**Comment by lns103** [comment]
删了，还是一样

**Comment by cjw1115** [comment]
你有没有外接显示器，在笔记本屏幕上播试试看

BR，
Jiawei
________________________________
发件人: lns103 ***@***.***>
发送时间: Saturday, July 1, 2023 1:44:06 PM
收件人: cjw1115/enable-chromium-dolbyvision-system-decoding ***@***.***>
抄送: CQ ***@***.***>; Comment ***@***.***>
主题: Re: [cjw1115/enable-chromium-dolbyvision-system-decoding] 切换杜比视界图像模式无效，且播放开始时不显示Dolby Vision logo (Issue #3)


删了，还是一样

―

**Comment by lns103** [comment]
就是用的笔记本屏幕，没有外接显示器，并且尝试了切换核显输出，依然如此

**Comment by cjw1115** [comment]
你播这个视频 https://b23.tv/RpPWyiO ，看看是不是真的送了dvh1.05.06的流过来，如果是的话，晚点我给你发个log收集工具，你收集下log我看看

BR，
Jiawei
________________________________
发件人: lns103 ***@***.***>
发送时间: Saturday, July 1, 2023 3:15:36 PM
收件人: cjw1115/enable-chromium-dolbyvision-system-decoding ***@***.***>
抄送: CQ ***@***.***>; Comment ***@***.***>
主题: Re: [cjw1115/enable-chromium-dolbyvision-system-decoding] 切换杜比视界图像模式无效，且播放开始时不显示Dolby Vision logo (Issue #3)


就是用的笔记本屏幕，没有外接显示器，并且尝试了切换核显输出，依然如此

―

**Comment by lns103** [comment]
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/38dce2e0-fb97-4d97-af70-d5d9884cf02b)

**Comment by cjw1115** [comment]
我teams上给你发下log收集工具.

**Comment by lns103** [comment]
> 我teams上给你发下log收集工具.

抱歉之前没有看到消息，现在可以吗？

**Comment by cjw1115** [comment]
> > 我teams上给你发下log收集工具.
> 
> 抱歉之前没有看到消息，现在可以吗？

发你邮箱了

**Comment by cjw1115** [comment]
@lns103 ，log 我看了下，看起来色彩配置文件有点问题。你检查以下你系统设置里这几个位置我看看

- 色彩配置文件是什么？下拉列表里都有什么选项
- 使用HDR有没有打开？

![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/13924086/60279107-a6df-4f7c-964c-267255ba9982)

**Comment by lns103** [comment]
没开HDR，如果开启HDR，自带播放器也不会显示logo
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/112349d0-69c9-48ee-a031-bdc637286360)
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/794675c4-bc72-4fd5-aed5-8bd982a63139)
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/2ae7918d-60a2-4d80-ab70-6b3ed158d285)
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/3cde4239-9aa5-43a9-ab69-8a9f57e69187)


这是所有的校色文件，是系统自带的，删掉也可以用x-rite云端恢复
[color_profile.zip](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/files/11928371/color_profile.zip)

(今天白天有事，可能无法及时回复)

**Comment by cjw1115** [comment]
你方便的话把这个目录下的所有文件打包发给我
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/13924086/5296bebc-beea-4a35-af36-afefbcb52a0f)

**Comment by lns103** [comment]
> 你方便的话把这个目录下的所有文件打包发给我 ![image](https://user-images.githubusercontent.com/13924086/250335433-5296bebc-beea-4a35-af36-afefbcb52a0f.jpeg)

已发邮箱

**Comment by cjw1115** [comment]
@lns103  麻烦再提供下 注册表 Computer\HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System\BIOS 下面的这几个字段
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/13924086/76b53a64-922e-4f8d-8dc3-83b327911dc1)

不要截图哈，复制出来

**Comment by lns103** [comment]
```
    SystemFamily    REG_SZ    Legion Y9000K2020H
    SystemManufacturer    REG_SZ    LENOVO
    SystemProductName    REG_SZ    81YW
    SystemSKU    REG_SZ    LENOVO_MT_81YW_BU_idea_FM_Legion Y9000K2020H
    SystemVersion    REG_SZ    Lenovo Legion Y9000K2020H
```

**Comment by cjw1115** [comment]
我建议你把显示器的驱动卸载掉, 先不要用第三方的色彩管理工具，然后去联想官网重新安装
https://newsupport.lenovo.com.cn/driveDownloads_detail.html?driveId=76329 

![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/13924086/cc71b088-928b-451b-b489-00e73f6c4977)

**Comment by lns103** [comment]
> 我建议你把显示器的驱动卸载掉, 先不要用第三方的色彩管理工具，然后去联想官网重新安装 https://newsupport.lenovo.com.cn/driveDownloads_detail.html?driveId=76329

这个x-rite是自带的，刚切回核显的时候，自带播放器也无法显示LOGO（之前卸载了核显驱动），用x-rite恢复了云端色彩配置之后自带播放器就有LOGO了
（现在暂时不方便操作，等晚一些的时候尝试了再更新情况）

**Comment by lns103** [comment]
重新安装显示器驱动以后正常了，画面模式也可以正确切换了，卸载之前我看了版本是一样的，不知道是什么导致的问题，感谢大佬帮助排查
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/15385c2f-74da-4bd5-9f9d-19fd8a23dd34)

**Comment by cjw1115** [comment]
你截个你的 color management 看看都有哪些icm

**Comment by lns103** [comment]
这。。。确实不一样了
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/6d020982-99cd-4268-ba0b-4f3399e3e078)

**Comment by lns103** [comment]
我又重新添加回了其它的色彩配置，并且重启之后也是能正常触发logo的状态
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/620ff3d0-b30a-4e07-8dd2-d46151198ae8)

**Comment by cjw1115** [comment]
应为Chromium 里 MediaFoundation 运行在一个低权限的沙箱里面，所以 MediaPlayer 能访问的一些配置到 Chromium里面不一定能访问。我猜大概是这个原因。
