### ISSUE TITLE
4096x2160的视频全屏播放异常

### ISSUE THREAD

**Issue by lns103** [cjw1115/enable-chromium-dolbyvision-system-decoding#6]
[BV1V14y1R7Rk](https://www.bilibili.com/video/BV1V14y1R7Rk) 这个视频打开杜比视界，全屏之后大小异常，手动选择16:9比例可以暂时解决。
屏幕为1920x1080，本地播放器全屏不存在问题
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/7f37f9aa-3cb5-48d7-9c41-85c54d433ac2)
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/0ec8b70b-6bcf-4e30-90c5-74d506992a9a)

**Comment by cjw1115** [comment]
你装这个新的版本试试看
[chromium_117.0.5882.0_clear_dolby_vision_atmos.exe](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/releases/download/clear_dolby_vision/chromium_117.0.5882.0_clear_dolby_vision_atmos.exe)

**Comment by lns103** [comment]
![image](https://github.com/cjw1115/enable-chromium-dolbyvision-system-decoding/assets/49310852/1c4cf269-5abd-4e22-bf7e-46f5e23ede84)
可以了，新版本没有这个问题了

**Comment by cjw1115** [comment]
那可能是chrome其他地方的问题导致的，新版我没改什么东西。
